"""In this conftest, we load the sample fixtures from a cached pipeline
generated by the test test_generate_cached_pipeline"""

import pytest

from . import get_cached_pipeline_path, load_from_cache


@pytest.fixture(scope="session")
def start_date():
    """A sample start date for the pipeline"""
    return "2021-01-04"


@pytest.fixture(scope="session")
def end_date():
    """A sample end date for the pipeline"""
    return "2021-01-29"


@pytest.fixture(scope="session")
def tickers():
    """A sample list of tickers"""
    return {"AAPL", "MSFT", "AMZN", "GOOGL"}


@pytest.fixture(scope="session")
def cached_pipeline_path(tickers, start_date, end_date, worker_id):
    """This fixture returns the path to the cached pipeline and evaluates the
    pipeline if necessary.

    worker_id: the id of the worker in pytest-xdist
    (remove this argument if you don't use pytest-xdist)
    """
    return get_cached_pipeline_path(tickers, start_date, end_date, worker_id)


@pytest.fixture(scope="session")
def yahoo_data(cached_pipeline_path):
    return load_from_cache(cached_pipeline_path, "yahoo_data")


@pytest.fixture(scope="session")
def closes(cached_pipeline_path):
    return load_from_cache(cached_pipeline_path, "closes")


@pytest.fixture(scope="session")
def volumes(cached_pipeline_path):
    return load_from_cache(cached_pipeline_path, "volumes")
