name: CI
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
  schedule:
    - cron: '0 11 * * 4'

jobs:
  skip_duplicate:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}

  pre-commit:
    needs: skip_duplicate
    if: ${{ needs.skip_duplicate.outputs.should_skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: pre-commit/action@v2.0.0

  test-pip:
    needs: skip_duplicate
    if: ${{ needs.skip_duplicate.outputs.should_skip == 'false' }}
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sample_pipeline/requirements.txt
          pip install -e sample_pipeline/
      - name: Setup TMPDIR
        run: echo "TMPDIR=${TMPDIR}" >> $GITHUB_ENV
      - name: Test with pytest
        run: pytest sample_pipeline --cov=./ --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v2
